name: CMake

on:
  push:
    branches: [ main ]

jobs:
  win-build-1:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - uses: ilammy/msvc-dev-cmd@v1
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2
    
    - name: Vcpkg
      run: |
        vcpkg install zlib:x64-windows
        vcpkg integrate install
      
    - name: Build wheels
      uses: pypa/cibuildwheel@v2.12.1
      env:
        CIBW_ARCHS_WINDOWS: AMD64
        CIBW_BUILD: cp*
        
    - uses: actions/upload-artifact@v3
      with:
        path: ./wheelhouse/*.whl
  
  mac-build-1:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: install cmake
        run: |
          brew install gcc
          brew install ninja
          ls -l /usr/local/bin | grep g++
          ls -l /usr/local/bin | grep gcc
          
      - name: test
        run: |
          echo $PATH
          which gcc
          which g++
          which ranlib
          which ar
          which cmake

      - name: Build wheels1
        uses: pypa/cibuildwheel@v2.12.1
        env:
          CIBW_BUILD: cp*
          CIBW_SKIP: cp38-*
          CIBW_ARCHS: x86_64 universal2 arm64
      
      - name: for py38
        run: |
          curl -o /tmp/Python38.pkg https://www.python.org/ftp/python/3.8.10/python-3.8.10-macos11.pkg
          sudo installer -pkg /tmp/Python38.pkg -target /
          sh "/Applications/Python 3.8/Install Certificates.command"

      - name: Build wheels2
        uses: pypa/cibuildwheel@v2.12.1
        env:
          CIBW_BUILD: cp38-*
          CIBW_ARCHS: x86_64 universal2 arm64

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl