name: CMake

on:
  push:
    branches: [ main ]

jobs:
  build1:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - uses: ilammy/msvc-dev-cmd@v1
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2
    
    #- name: Install Server-Media-Foundation
    #  shell: powershell
    #  run: |
    #    Install-WindowsFeature Server-Media-Foundation
    
    - name: Vcpkg
      run: |
        vcpkg install zlib:x64-windows
        vcpkg integrate install
      #env:
      #  VCPKG_LIBRARY_LINKAGE: dynamic
      #  VCPKG_CRT_LINKAGE: dynamic


    #- name: Create directory
    #  run: mkdir ${{github.workspace}}\build
    #  shell: cmd

    # - name: Install
    #   working-directory: ${{github.workspace}}/build
    #   run: powershell -Command "(Invoke-WebRequest -Uri https://git.io/JnHTY -OutFile install_zlib.bat)"; ./install_zlib.bat; del install_zlib.bat
    #   shell: cmd

    - name: Test4
      run: |
        powershell -Command "(Get-Item C:\vcpkg\installed\x64-windows\bin\*)"
        powershell -Command "(Get-Item C:\vcpkg\installed\x64-windows\lib\*)"
        powershell -Command "(Copy-Item C:\vcpkg\installed\x64-windows\bin\*.dll C:\vcpkg\installed\x64-windows\lib\)"
        powershell -Command "(Get-Item C:\vcpkg\installed\x64-windows\include\*)"
        powershell -Command "(Get-Command python)"
        powershell -Command "(python -m sysconfig)"
        powershell -Command "(Get-Item C:\hostedtoolcache\windows\Python\3.11.2\*)"
        powershell -Command "(Get-Item C:\hostedtoolcache\windows\Python\3.11.2\x64\*)"
        powershell -Command "(Get-Item C:\hostedtoolcache\windows\Python\3.11.2\x64\libs\*)"
        
      shell: cmd
    
    #- name: test mcberepair1
    #  working-directory: ${{ github.workspace }}/pybedrock/clib
    #  run: |
    #   powershell -Command "(Set-Item Env:LIB 'C:\hostedtoolcache\windows\Python\3.11.2\x64\libs')"
    #    powershell -Command "(Set-Item Env:LIBPATH 'C:\hostedtoolcache\windows\Python\3.11.2\x64\libs')"
    #    powershell -Command "($ENV:LIBPATH)"
    #    powershell -Command "($ENV:LIB)"
    #    powershell -Command "(Copy-Item ../../patch/CMakeLists.txt ./leveldb-mcpe/CMakeLists.txt)"
    #    cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DVCPKG_TARGET_TRIPLET=x64-windows -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake
    #    cmake --build build --config Release
    #  shell: cmd
    #  env: 
    #    LIB:  C:\hostedtoolcache\windows\Python\3.11.2\x64\libs
    #    LIBPATH:  C:\hostedtoolcache\windows\Python\3.11.2\x64\libs

    #- name: test mcberepair2
    #  working-directory: ${{ github.workspace }}\mcberepair
    #  run: |
    #    powershell -Command "(Get-Location)"
    #    powershell -Command "(Get-Item .\*)"
    #    cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DVCPKG_TARGET_TRIPLET=x64-windows -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake
    #    cmake --build build --config Release
      
    #  shell: cmd
    
    # - name: test mcberepair2
    #  working-directory: ${{ github.workspace }}/pybedrock/clib
    #  run: |
    #    powershell -Command "(Get-Location)"
    #    powershell -Command "(Get-Item .\build\*)"
    #    powershell -Command "(Get-Item .\build\Release\*)"
    #    
    #  shell: cmd

    - name: Build wheels
      uses: pypa/cibuildwheel@v2.12.1
      env:
        CIBW_ARCHS_WINDOWS: AMD64
    
    - uses: actions/upload-artifact@v3
      with:
        path: ./wheelhouse/*.whl
  
  build2:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - uses: ilammy/msvc-dev-cmd@v1
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2
    
    - name: Vcpkg
      run: |
        vcpkg install zlib:x64-windows
        vcpkg integrate install

    - name: Test4
      run: |
        powershell -Command "(Get-Item C:\vcpkg\installed\x64-windows\bin\*)"
        powershell -Command "(Get-Item C:\vcpkg\installed\x64-windows\lib\*)"
        powershell -Command "(Copy-Item C:\vcpkg\installed\x64-windows\bin\*.dll C:\vcpkg\installed\x64-windows\lib\)"
        powershell -Command "(Get-Item C:\vcpkg\installed\x64-windows\include\*)"
        powershell -Command "(Get-Command python)"
        powershell -Command "(python -m sysconfig)"
        powershell -Command "(Get-Item C:\hostedtoolcache\windows\Python\3.11.2\*)"
        powershell -Command "(Get-Item C:\hostedtoolcache\windows\Python\3.11.2\x64\*)"
        powershell -Command "(Get-Item C:\hostedtoolcache\windows\Python\3.11.2\x64\libs\*)"
        
      shell: cmd

    - name: Build wheels
      uses: pypa/cibuildwheel@v2.12.1
      env:
        CIBW_ARCHS_WINDOWS: ARM64
    
    - uses: actions/upload-artifact@v3
      with:
        path: ./wheelhouse/*.whl
  
  build3:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - uses: ilammy/msvc-dev-cmd@v1
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2
    
    - name: Vcpkg
      run: |
        vcpkg install zlib:x64-windows
        vcpkg integrate install

    - name: Test4
      run: |
        powershell -Command "(Get-Item C:\vcpkg\installed\x64-windows\bin\*)"
        powershell -Command "(Get-Item C:\vcpkg\installed\x64-windows\lib\*)"
        powershell -Command "(Copy-Item C:\vcpkg\installed\x64-windows\bin\*.dll C:\vcpkg\installed\x64-windows\lib\)"
        powershell -Command "(Get-Item C:\vcpkg\installed\x64-windows\include\*)"
        powershell -Command "(Get-Command python)"
        powershell -Command "(python -m sysconfig)"
        powershell -Command "(Get-Item C:\hostedtoolcache\windows\Python\3.11.2\*)"
        powershell -Command "(Get-Item C:\hostedtoolcache\windows\Python\3.11.2\x64\*)"
        powershell -Command "(Get-Item C:\hostedtoolcache\windows\Python\3.11.2\x64\libs\*)"
        
      shell: cmd

    - name: Build wheels
      uses: pypa/cibuildwheel@v2.12.1
      env:
        CIBW_ARCHS_WINDOWS: x86
    
    - uses: actions/upload-artifact@v3
      with:
        path: ./wheelhouse/*.whl
