name: CMake

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Create directory
      run: mkdir ${{github.workspace}}\build
      shell: cmd

    - name: Install
      working-directory: ${{github.workspace}}/build
      run: powershell -Command "(Invoke-WebRequest -Uri https://git.io/JnHTY -OutFile install_zlib.bat)"; ./install_zlib.bat; del install_zlib.bat
      shell: cmd

    - name: Test
      run: |
        if NOT exist "%PROGRAMFILES%"\zlib\lib\zlib.lib exit 1
        if NOT exist "%PROGRAMFILES%"\zlib\bin\zlib.dll exit 1
        if NOT exist "%PROGRAMFILES%"\zlib\include\zconf.h exit 1
        if NOT exist "%PROGRAMFILES%"\zlib\include\zlib.h exit 1
        if NOT exist "%PROGRAMFILES%"\zlib\lib\zlib.lib exit 1
      shell: cmd
    
    - name: Build wheels
        uses: pypa/cibuildwheel@v2.12.1