name: CMake

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2
    
    - name: Install Server-Media-Foundation
      shell: powershell
      run: |
        Install-WindowsFeature Server-Media-Foundation
    
    - name: Vcpkg
      run: |
        vcpkg install zlib:x64-windows
        vcpkg integrate install
      #env:
      #  VCPKG_LIBRARY_LINKAGE: dynamic
      #  VCPKG_CRT_LINKAGE: dynamic


    #- name: Create directory
    #  run: mkdir ${{github.workspace}}\build
    #  shell: cmd

    # - name: Install
    #   working-directory: ${{github.workspace}}/build
    #   run: powershell -Command "(Invoke-WebRequest -Uri https://git.io/JnHTY -OutFile install_zlib.bat)"; ./install_zlib.bat; del install_zlib.bat
    #   shell: cmd

    - name: Test0
      run: |
        if NOT exist C:\vcpkg\installed\x64-windows\lib\zlib.lib exit 1
      shell: cmd

    - name: Test1
      run: |
        if NOT exist C:\vcpkg\installed\x64-windows\include\zconf.h exit 1
      shell: cmd

    - name: Test2
      run: |
        if NOT exist C:\vcpkg\installed\x64-windows\include\zlib.h exit 1
      shell: cmd

    - name: Test3
      run: |
        if NOT exist C:\vcpkg\installed\x64-windows\bin\zlib1.dll exit 1
      shell: cmd

    - name: Test4
      run: |
        powershell -Command "(Get-Item C:\vcpkg\installed\x64-windows\bin\*)"
        powershell -Command "(Get-Item C:\vcpkg\installed\x64-windows\lib\*)"
        powershell -Command "(Get-Item C:\vcpkg\installed\x64-windows\include\*)"
      shell: cmd
    
    - name: Build wheels
      uses: pypa/cibuildwheel@v2.12.1
    
    - uses: actions/upload-artifact@v3
      with:
        path: ./wheelhouse/*.whl
